# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5yF7Kp_PIWj2tKP9lsmpsvgziOkp2CR
"""

temp= [80, 72, 95, 82, 79, 72, 85]
ctemp = []

for l in temp:
  ctemp.append((l - 32)  *5 / 9)

print([round(c, 2) for c in ctemp])