# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-7BAEHFGK0cORwmxOhNmYcDYQA8KtKV
"""

datos = {'nombre':'Joseph de Jesus Lemus Pineda',
         'matricula':'231690508-0',
         'edad':17,
         'peso':65,
         'numero':'7447521466',
         'domicilio':'Calle Violeta #59',
         'carrera':'CDIA'}

print(datos)

print(datos['nombre'])

datos['nombre'] = 'Alberto Javier Ricardo Benitez Alegria'
print(datos)

for list in datos:
  print (list)

datos.pop('carrera')
print(datos)

datos.clear()
print(datos)